remote_theme: just-the-docs/just-the-docs
title: Swiss Routing
description: Swiss Routing - A Bitcoin Lightning Network Node
color_scheme: light
plugins:
  - jekyll-gist

# Include common verification and config files
include: [".well-known"]

# Aux links for the upper right navigation
aux_links:
  "Swiss Routing on Twitter":
    - "https://twitter.com/SwissRouting"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/swissrouting/swissrouting.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
